spring.application.name=NOTIFICATION-SERVICE

server.port=${PORT:8006}

spring.config.import=optional:configserver:https://config-server-85or.onrender.com

eureka.client.service-url.defaultZone=https://eureka-server-92rv.onrender.com/eureka/

management.endpoints.web.exposure.include=*