spring.application.name=ORDER-SERVICE
server.port=8005

spring.config.import=optional:configserver:http://localhost:8001

eureka.client.service-url.defaultZone=http://localhost:8000/eureka/

spring.datasource.url=jdbc:postgresql://dpg-d9qlqk2jnfac73doh5o0-a.singapore-postgres.render.com:5432/onlineshopping_xlkt?sslmode=require
spring.datasource.username=uday
spring.datasource.password=kcogzgWfOwV1Yrx2z1edZtamGkDw5J74
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/index.html