spring.application.name=API-GATEWAY
server.port=8002

spring.config.import=optional:configserver:http://config-server:8001

eureka.client.service-url.defaultZone=http://eureka-server:8000/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

management.endpoints.web.exposure.include=*