spring.application.name=EUREKA-SERVER

server.port=${PORT:8000}

eureka.client.register-with-eureka=false

eureka.client.fetch-registry=false

eureka.client.service-url.defaultZone=

management.endpoints.web.exposure.include=*