spring.application.name=API-GATEWAY
server.port=${PORT:8002}

eureka.client.service-url.defaultZone=http://eureka-server:8000/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

management.endpoints.web.exposure.include=*