spring.application.name=CONFIG-SERVER

server.port=${PORT:8001}

spring.cloud.config.server.git.uri=https://github.com/uday348/online-shopping-system

spring.cloud.config.server.git.default-label=main

spring.cloud.config.server.git.clone-on-start=true

spring.cloud.config.server.git.skip-ssl-validation=true

spring.cloud.config.server.git.search-paths=config-server/src/main/resources

eureka.client.service-url.defaultZone=https://eureka-server-92rv.onrender.com/eureka/

management.endpoints.web.exposure.include=*