spring.application.name=NOTIFICATION-SERVICE

server.port=${PORT:8006}

eureka.client.service-url.defaultZone=https://eureka-server-92rv.onrender.com/eureka/

management.endpoints.web.exposure.include=*